In [2]:
# Archivo base de datos limpio

# /content/MBERNALES_CICLONES.csv

import pandas as pd

df = pd.read_csv('/content/MBERNALES_CICLONES.csv')

df.head()

,Count ;Year;Start Month;Gender;Name;Country;Region;OFDA/BHA Response;AID Contribution ('000 US$);Magnitude (Kph);Total Deaths;No. Injured;No. Affected;No. Homeless;Total Affected;Reconstruction Costs ('000 US$);Reconstruction Costs,Adjusted ('000 US$);Insured Damage ('000 US$);Insured Damage,Adjusted ('000 US$);Total Damage ('000 US$);Total Damage,Adjusted ('000 US$)
0,1;1928;9;;San Felipe / Okeechobee ;Puerto Rico...,NaN,NaN,NaN
1,2;1928;9;;Felipe;Guadeloupe;Americas;No;;;2000...,NaN,NaN,NaN
2,3;1930;9;;San Zenon;Dominican Republic;America...,NaN,NaN,NaN
3,4;1932;9;;San Ciprian;Puerto Rico;Americas;No;...,NaN,NaN,NaN
4,5;1935;10;;Jeremie & Jacmel;Haiti;Americas;No;...,NaN,NaN,NaN

In [3]:
import csv

# Abre el archivo CSV original y lee su contenido
with open('/content/MBERNALES_CICLONES.csv', 'r', encoding='utf-8') as archivo_entrada:
    lector_csv = csv.reader(archivo_entrada, delimiter=';')
    filas = list(lector_csv)

# Escribe el contenido en un nuevo archivo CSV con comas como delimitador
with open('archivo_modificado.csv', 'w', encoding='utf-8', newline='') as archivo_salida:
    escritor_csv = csv.writer(archivo_salida, delimiter=',')
    escritor_csv.writerows(filas)

print("Archivo modificado exitosamente.")

Archivo modificado exitosamente.

In [4]:
df = pd.read_csv('/content/archivo_modificado.csv')

df.head()

,Count,Year,Start Month,Gender,Name,Country,Region,OFDA/BHA Response,AID Contribution ('000 US$),Magnitude (Kph),...,No. Injured,No. Affected,No. Homeless,Total Affected,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)"
0,1,1928,9.0,NaN,San Felipe / Okeechobee,Puerto Rico,Americas,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000,885897
1,2,1928,9.0,NaN,Felipe,Guadeloupe,Americas,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1930,9.0,NaN,San Zenon,Dominican Republic,Americas,No,NaN,NaN,...,6000.0,6000.0,NaN,12000.0,NaN,NaN,NaN,NaN,40000,729937
3,4,1932,9.0,NaN,San Ciprian,Puerto Rico,Americas,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30000,672240
4,5,1935,10.0,NaN,Jeremie & Jacmel,Haiti,Americas,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# filtrar las filas del año 1930

df.loc[df['Year'] == 1930]

,Count,Year,Start Month,Gender,Name,Country,Region,OFDA/BHA Response,AID Contribution ('000 US$),Magnitude (Kph),...,No. Injured,No. Affected,No. Homeless,Total Affected,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)"
2,3,1930,9.0,NaN,San Zenon,Dominican Republic,Americas,No,NaN,NaN,...,6000.0,6000.0,NaN,12000.0,NaN,NaN,NaN,NaN,40000,729937